#!/bin/bash


if [ $(uname) == "Darwin" ]; then
  gsed 's/;\([a-z]\)\([A-Za-z]*\)/;\u\1\2/g' $1 | gsed 's/ \([a-z]\)\([A-Za-z]*\)/ \u\1\2/g' | gsed 's/(\([a-z]\)\([A-Za-z]*\)/(\u\1\2/g' 
else
  sed 's/;\([a-z]\)\([A-Za-z]*\)/;\u\1\2/g' $1 | sed 's/ \([a-z]\)\([A-Za-z]*\)/ \u\1\2/g' | sed 's/(\([a-z]\)\([A-Za-z]*\)/(\u\1\2/g' 
fi

